### GENERAL SETTINGS ###

# Site settings
title: WAMPUM
description: "We beileve in eCommerce for all!  Wampum helps any legitimate business accept electronic payments (Cryptocurrency) with or without a Bank."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/wampum" #important: start with /
url: "https://jaythanelam.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#0B4069" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#ffffff" #"#33004D"
  link: "#1EC5A2"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

  dark_brown: "#63594D"
  medium_brown: "#988976"
  light_brown: "#EDEAE6"
  superlt_brown: "F6F4F2"
  white: "#ffffff"
  teal: "#1EC5A2"
  red: "#FA5040"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/cryptowampum/
  - title: twitter
    url: https://twitter.com/CryptoWampum
  - title: bitcoin
    url: 
  - title: angellist
    url: https://angel.co/wampum-2

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 9200 E. Mineral Ave, Suite 100
    - 80112, Centennial,
    - United States.
email: info@cryptowampum.com
tel: (303) 997-2595


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "We believe that eCommerce technologies should be available to anyone doing legitimate business. We help our customers accept Bitcoin payments with or without the use of a local bank."
    author: Marcel Newman
    position: Founder - BLACKTIE.CO
