### GENERAL SETTINGS ###

# Site settings
title: "Wampei eCommerce for all"
description: "We beileve in eCommerce for all!  Wampei helps any legitimate business accept electronic payments (Cryptocurrency) with or without a Bank."
analytics: "UA-70441646-2"  #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://cryptowampum.com"
cannonical_url: "http://cryptowampum.com"
author: "Wampei"
twitter:
  username: "cryptowampum"

facebook:
 app_id: "251251262032068"
 publisher: "251251262032068"
 admins: "251251262032068"
 
logo: "/assets/ico/favicon-32x32.png"

social:
  name: Wampei
  links:
    - https://twitter.com/CryptoWampum
    - https://www.facebook.com/cryptowampum/
    - https://angel.co/wampum-2
    - https://www.linkedin.com/company/18014266/



# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#0B4069" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#33004D" #"#ffffff"
  link: "#1EC5A2"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

  dark_brown: "#63594D"
  medium_brown: "#988976"
  light_brown: "#EDEAE6"
  superlt_brown: "F6F4F2"
  white: "#ffffff"
  teal: "#1EC5A2"
  red: "#FA5040"

# Making projects separate from posts
collections:
  projects:
    output: false
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/cryptowampum/
  - title: twitter
    url: https://twitter.com/CryptoWampum
  - title: angellist
    url: https://angel.co/wampum-2
  - title: linkedin
    url: https://www.linkedin.com/company/18014266/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 9200 E. Mineral Ave, Suite 100
    - 80112, Centennial,
    - United States.
email: info@cryptowampum.com
tel: (303) 997-2595


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Russell Castagnaro
    position: CEO and Cofounder
    text: Russell is a visionary whose vast technical knowledge and practical, people-centric approach over the last 23 years has enabled the teams he has led to change the landscape of electronic commerce, enterprise software development and government operations.  
    img: RussellHeadshotClose.jpg
    social:
      - title: envelope #use for email address
        url: mailto:russell@cryptowampum.com
      - title: twitter
        url: http://twitter.com/rcastag
  - name: Matt Skoda
    position: CTO and Cofounder
    text: Matthew has vast experience in military, ecommerce, cryptography and government technology solutions.    
    img: MattSqAloha.jpg
    social:
      - title: envelope #use for email address
        url: mailto:matt@cryptowampum.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Alexis Swann
    position: Director of Business Development
    text: Responsible for identifying partners (eCommerce platforms and Point-of-Sale providers) who want to extend their reach in the eCommerce world.  Leverage technical knowledge, experience in Healthcare and intimate understanding of operations to position Wampei business partners to make the most of cryptocommerce and expand their customer base.
    img: LexHeadShotSq.jpg
    social:
      - title: envelope #use for email address
        url: mailto:alexis@cryptowampum.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Jaythan Elam
    position: Director of UX
    text: Jaythan has extensive experience spanning marketing and product development platforms – including branding, information architecture, and product focused user experience design for both web and mobile environments. His aesthetics reveal a love for all things typographic, minimalistic geometry, and clever thought provoking design solutions.    
    img: Jaythan.png
    social:
      - title: envelope #use for email address
        url: mailto:jaythan@jointley.com
      - title: twitter
        url: http://twitter.com/jaythan



# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We believe that eCommerce (electronic payments) should be available to all. We help our customers accept crypto payments with or without the use of a bank."

# Testimonial content. Shown on Home and About page.

    
plugins:
 - jekyll-seo-tag
 - jekyll-sitemap

